// Generated by Wrangler on Wed Sep 04 2024 09:14:11 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string;
  CLERK_SECRET_KEY: string;
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: string;
  NEXT_PUBLIC_GOOGLE_MAPS_MAPID: string;
  BUZZTRIP_BUCKET: R2Bucket;
  BUZZTRIP_DATABASE: D1Database;
}
