// Generated by Wrangler on Thu Sep 12 2024 19:18:59 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	CLOUDFLARE_D1_ACCOUNT_ID: string;
	CLOUDFLARE_D1_API_TOKEN: string;
	CLERK_SECRET_KEY: string;
	CLERK_WEBHOOK_SECRET: string;
	NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string;
	NEXT_PUBLIC_CLERK_SIGN_IN_URL: string;
	NEXT_PUBLIC_CLERK_SIGN_UP_URL: string;
	NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: string;
	NEXT_PUBLIC_GOOGLE_MAPS_MAPID: string;
	BUZZTRIP_BUCKET: R2Bucket;
	BUZZTRIP_DATABASE: D1Database;
}
