blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/jacobsamo/BuzzTrip/discussions
    about: Ask questions or start discussions about BuzzTrip
  - name: Security Vulnerability
    url: https://github.com/jacobsamo/BuzzTrip/security/advisories/new
    about: Report a security vulnerability privately
