name = "api"
compatibility_date = "2024-12-12"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.ts"
minify = true
workers_dev = false

[dev]
port = 8181


[observability]
enabled = true

# [env.development]
# name = "dev-api"
# route = { pattern = "dev-api.buzztrip.co/*", zone_name = "buzztrip.co" }


# [env.production]
# name = "api"
# route = { pattern = "api.buzztrip.co/*", zone_name = "buzztrip.co" }


# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "BUZZTRIP_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
