name = "api"
compatibility_date = "2024-10-05"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.ts"
minify = true
workers_dev = false


[dev]
port = 8181
# ip = "0.0.0.0" #used to access the api from the mobile app
local_protocol = "https"



[env.production]
name = "api"
route = { pattern = "api.buzztrip.co/*", zone_name = "buzztrip.co" }


# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true